AWSTemplateFormatVersion: 2010-09-09
Description: Baseline IAM resources for new account

Parameters:
  AdminUsername:
    Type: String
    Description: Username for the Admin user
  AdminPassword:
    Type: String
    NoEcho: true
    MinLength: 1
    Description: Password for the Admin user
  NewRoleArn:
    Type: String
    Description: ARN of the NewRole


Resources:
  Admin:
    Type: 'AWS::IAM::User'
    Properties:
      UserName: !Ref AdminUsername
      Path: /
      LoginProfile:
        Password: !Ref AdminPassword

  Administrators:
    Type: 'AWS::IAM::Group'
    Properties:
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AdministratorAccess"
      GroupName: Administrators
      Path: /


  AddUserToGroup:
    Type: 'AWS::IAM::UserToGroupAddition'
    Properties:
      GroupName: !Ref Administrators
      Users:
        - !Ref Admin

# create rest of the resources here