AWSTemplateFormatVersion: 2010-09-09
Description: Baseline  resources for new account

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: VPCTemplateURL
        Parameters:
          - VPCTemplateURL
    ParameterGroups:
      - Label:
          default: Environment
        Parameters:
          - Environment
      - Label:
          default: Business Unit
        Parameters:
          - BusinessUnit
      - Label:
          default: VPC and Subnet Configuration
        Parameters:
          - VPCCidrBlock
          - PresentationSubnetACidr
          - PresentationSubnetBCidr
          - PresentationSubnetCCidr
          - ApplicationSubnetACidr
          - ApplicationSubnetBCidr
          - ApplicationSubnetCCidr
          - DataSubnetACidr
          - DataSubnetBCidr
          - DataSubnetCCidr
      - Label:
          default: Child Templates
        Parameters:
          - DHCPTemplateURL
          - VPGTemplateURL
          - PrivateNaclTemplateURL
          - PublicNaclTemplateURL
          - RouteTableTemplateURL
          - SubnetTemplateURL
          - IGTemplateURL
          - NATTemplateURL
    ParameterLabels:
      VPCCidrBlock:
        default: VPC CIDR
      PresentationSubnetACidr:
        default: Web A CIDR
      PresentationSubnetBCidr:
        default: Web B CIDR
      PresentationSubnetCCidr:
        default: Web C CIDR
      ApplicationSubnetACidr:
        default: App A CIDR
      ApplicationSubnetBCidr:
        default: App B CIDR
      ApplicationSubnetCCidr:
        default: App C CIDR
      DataSubnetACidr:
        default: Data A CIDR
      DataSubnetBCidr:
        default: Data B CIDR
      DataSubnetCCidr:
        default: Data C CIDR
      VPCTemplateURL:
        default: VPCTemplateURL
Parameters:
  VPCTemplateURL:
    Type: String
    Description: URL of the CloudFormation template for the VPC
    Default: 

  BusinessUnit:
    Default: UNSWIT-SSS
    Description: Enter the business unit that will own the VPC e.g., finance
    Type: String
  Environment:
    AllowedValues:
      - prod
      - nonprod
    ConstraintDescription: Must be one of the following prod, nonprod (lower Case)
    Default: nonprod
    Description: Enter the Environment that this VPC will hold (prod, nonprod)
    Type: String
  VPCCidrBlock:
    Type: String
    Default: 10.118.224.0/21
    Description: Enter the CIDR of the VPC e.g 10.118.224.0/21
    AllowedPattern: (\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})
    ConstraintDescription: Must be a valid IP CIDR range of the form x.x.x.x/x
  ApplicationSubnetACidr:
    AllowedPattern: (\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})
    ConstraintDescription: Must be a valid IP CIDR range of the form x.x.x.x/x
    Default: 10.118.225.128/25
    Description: Enter the CIDR of the App subnet A e.g 10.118.225.128/25
    Type: String
  ApplicationSubnetBCidr:
    AllowedPattern: (\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})
    ConstraintDescription: Must be a valid IP CIDR range of the form x.x.x.x/x
    Default: 10.118.226.0/25
    Description: Enter the CIDR of the App subnet B e.g 10.118.226.0/25
    Type: String
  ApplicationSubnetCCidr:
    AllowedPattern: (\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})
    ConstraintDescription: Must be a valid IP CIDR range of the form x.x.x.x/x
    Default: 10.118.226.128/25
    Description: Enter the CIDR of the App subnet C e.g 10.118.226.128/25
    Type: String
  DataSubnetACidr:
    AllowedPattern: (\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})
    ConstraintDescription: Must be a valid IP CIDR range of the form x.x.x.x/x
    Default: 10.118.227.0/25
    Description: Enter the CIDR of the Data Subnet A e.g 10.118.227.0/25
    Type: String
  DataSubnetBCidr:
    AllowedPattern: (\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})
    ConstraintDescription: Must be a valid IP CIDR range of the form x.x.x.x/x
    Default: 10.118.227.128/25
    Description: Enter the CIDR of the Data Subnet B e.g 10.118.227.128/25
    Type: String
  DataSubnetCCidr:
    AllowedPattern: (\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})
    ConstraintDescription: Must be a valid IP CIDR range of the form x.x.x.x/x
    Default: 10.118.228.0/25
    Description: Enter the CIDR of the Data Subnet C e.g 10.118.228.0/25
    Type: String
  PresentationSubnetACidr:
    AllowedPattern: (\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})
    ConstraintDescription: Must be a valid IP CIDR range of the form x.x.x.x/x.
    Default: 10.118.224.0/25
    Description: Enter the CIDR of the Web Subnet A e.g 10.118.224.0/25
    Type: String
  PresentationSubnetBCidr:
    AllowedPattern: (\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})
    ConstraintDescription: Must be a valid IP CIDR range of the form x.x.x.x/x.
    Default: 10.118.224.128/25
    Description: Enter the CIDR of the Web subnet B e.g 10.118.224.128/25
    Type: String
  PresentationSubnetCCidr:
    AllowedPattern: (\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})
    ConstraintDescription: Must be a valid IP CIDR range of the form x.x.x.x/x.
    Default: 10.118.225.0/25
    Description: Enter the CIDR of the Web subnet C e.g 10.118.225.0/25
    Type: String
  DHCPTemplateURL:
    Default: https://s3-ap-southeast-2.amazonaws.com/unswit-sss-nprod-templates/workspace/dhcp-options.json
    Description: Enter DHCP options template path
    Type: String
  VPGTemplateURL:
    Default: https://s3-ap-southeast-2.amazonaws.com/unswit-sss-nprod-templates/workspace/vpg.json
    Description: Enter Virtual Private Gateway template path
    Type: String
  PrivateNaclTemplateURL:
    Default: https://s3-ap-southeast-2.amazonaws.com/unswit-sss-nprod-templates/workspace/private-nacls.json
    Description: Enter Private NACLs template path
    Type: String
  PublicNaclTemplateURL:
    Default: https://s3-ap-southeast-2.amazonaws.com/unswit-sss-nprod-templates/workspace/public-nacls.json
    Description: Enter Public NACLs template path
    Type: String
  RouteTableTemplateURL:
    Default: https://s3-ap-southeast-2.amazonaws.com/unswit-sss-nprod-templates/workspace/routetables.json
    Description: Enter Route Tables template path
    Type: String
  SubnetTemplateURL:
    Default: https://s3-ap-southeast-2.amazonaws.com/unswit-sss-nprod-templates/workspace/subnets.json
    Description: Enter Subnets template path
    Type: String
  IGTemplateURL:
    Default: https://s3-ap-southeast-2.amazonaws.com/unswit-sss-nprod-templates/workspace/ig.json
    Description: Enter Internet Gateway template path
    Type: String
  NATTemplateURL:
    Default: https://s3-ap-southeast-2.amazonaws.com/unswit-sss-nprod-templates/workspace/natg.json
    Description: Enter NAT Gateway template path
    Type: String

Resources:
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Ref VPCTemplateURL
      TimeoutInMinutes: '60'
      Parameters:
        BusinessUnit: !Ref 'BusinessUnit'
        Environment: !Ref 'Environment'
        PresentationSubnetACidr: !Ref 'PresentationSubnetACidr'
        PresentationSubnetBCidr: !Ref 'PresentationSubnetBCidr'
        PresentationSubnetCCidr: !Ref 'PresentationSubnetCCidr'
        ApplicationSubnetACidr: !Ref 'ApplicationSubnetACidr'
        ApplicationSubnetBCidr: !Ref 'ApplicationSubnetBCidr'
        ApplicationSubnetCCidr: !Ref 'ApplicationSubnetCCidr'
        DataSubnetACidr: !Ref 'DataSubnetACidr'
        DataSubnetBCidr: !Ref 'DataSubnetBCidr'
        DataSubnetCCidr: !Ref 'DataSubnetCCidr'
